### ISSUE TITLE
Got App Key and Secret, can connect to MQTT broker, no data

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [Zendure/developer-device-data-report#21]
Hi,
I successfully created my appkey and secret (registered as developer). I can now connect to mqtt.zen-iot.com with the MQTT Explorer, but I do not see any data/topics coming from my SolarFlow device?
I noticed that SolarFlow is connecting to mq.zen-iot.com (another mqtt broker?) and not the mqtt.zen-iot.com.
trying to connect to mq.zen-iot.com with the dev credentials doesn't work (expected)
Is this supposed to work for SolarFlow as well?

<img width="887" alt="image" src="https://github.com/Zendure/developer-device-data-report/assets/10830223/7a3a58a4-e836-4d70-bb55-1a0f56b65dca">

**Comment by z-master42** [comment]
You need to subscribe to a topic. On the configuration page of the connection, you must click on advanced and enter _yourusername_/# as the topic and add it.

**Comment by reinhard-brandstaedter** [comment]
Got that, figured! Thanks!
