### ISSUE TITLE
no data in MQTT since June 16 

### ISSUE THREAD

**Issue by Be4fun** [Zendure/developer-device-data-report#51]
No data being published in mqtt. Working until June 16th around 11PM CET
API registration is "successful operations"

**Comment by python1185** [comment]
Same here

**Comment by TheHangMan97** [comment]
Same here

**Comment by pascalbourges** [comment]
hi, same issue from 17 june 4 hour AM french timezone

**Comment by ChristophA** [comment]
Same here since 4 am.

**Comment by Astromechdroide** [comment]
We also have no connection here in Europe.
{"code":400,"success":false,"data":{},"msg":"Please bind the device first"}* Connection #0 to host app.zendure.tech left intact

**Comment by ge8020** [comment]
Can confirm that. Austria-Europe
No Data in MQTT Explorer, but App & Shelly Connection are working fine

**Comment by H0d0rKF** [comment]
Same Problem Germany Europe

**Comment by jeff1975** [comment]
Seit gestern kein Mqtt von Zendure Europa

**Comment by seppkurt** [comment]
same here

**Comment by Stievie72** [comment]
Was ist das für ein Service... da denkste zahlste bisschen mehr und dann kümmern die sich und dann wird es nicht einmal Kommentiert. Das nenne ich Kundenservice.

**Comment by programmieramt** [comment]
> Was ist das für ein Service... da denkste zahlste bisschen mehr und dann kümmern die sich und dann wird es nicht einmal Kommentiert. Das nenne ich Kundenservice.

Wenn ich das richtig verstehe wird hier eine Dev-Schnittstelle genutzt. Die Kaufentscheidung anhand der Verfügbarkeit einer Dev-Api zu treffen ist wohl nicht ideal.
Die App funktioniert ja die ganze Zeit. Morgen beginnt soweit ich weiß die Intersolar und vermutlich muss da noch mal was fertig gemacht werden bevor die neuen Geräte gezeigt werden.

**Comment by Stievie72** [comment]
> > Was ist das für ein Service... da denkste zahlste bisschen mehr und dann kümmern die sich und dann wird es nicht einmal Kommentiert. Das nenne ich Kundenservice.
> 
> Wenn ich das richtig verstehe wird hier eine Dev-Schnittstelle genutzt. Die Kaufentscheidung anhand der Verfügbarkeit einer Dev-Api zu treffen ist wohl nicht ideal. Die App funktioniert ja die ganze Zeit. Morgen beginnt soweit ich weiß die Intersolar und vermutlich muss da noch mal was fertig gemacht werden bevor die neuen Geräte gezeigt werden.

Na dir Kaufentscheidung beinhaltet meines Erachtens nsch auch dir zur Verfügung gestellten Schnittstellen. Auch gerade wenn man solche Anlagen in eine smarte Hausinstallation integrieren möchte. 
Aber gut, mir geht es ja auch hauptsächlich um die Reaktion auf Kundenanfragen und Meldungen von Problemen. Da sollte es ein mindestens sein, solche Anfragen nicht einfach unkommentiert stehen zu lassen. Selbst wenn die Antwort nur beinhaltet, daß man das Problem sichtet, sobald die Zeit es zulässt. Aber 0 Reaktion setzt halt kein gutes Licht auf den Support. Würde ich so mit meinen Kunden umgehen,  muss ich mich nicht wundern, wenn der momentane Rekordumsatz irgendwann schwindet... aber gut, andere Baustelle ;)

**Comment by H0d0rKF** [comment]
Bei mir kommen wieder Daten an.

**Comment by python1185** [comment]
Seit 0800 kommen wieder Daten an.

**Comment by Stievie72** [comment]
Hier auch ;)

**Comment by jeff1975** [comment]
Danke Daten Ok

**Comment by Be4fun** [comment]
Switched to global dev Server and Hope the information on changes will improve in the Future

**Comment by jaegerschnitzel** [comment]
Es wurde ja vor ca. einem Jahr gesagt, dass die Daten zukünftig auch lokal abgegriffen werden können. Gibts dazu Neuigkeiten?
